name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: NPM install
      run: npm install
    - name: NPM build
      run: |
        echo Building...,
        npm run build
